name: Java Static Analysis

on: [push, pull_request]

jobs:
  inspect-code:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup tools
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.55.0/pmd-bin-6.55.0.zip
          unzip pmd-bin-6.55.0.zip
          curl -L -o checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.21.4/checkstyle-10.21.4-all.jar

      - name: Checkstyle
        run: java -jar checkstyle.jar -c /google_checks.xml $(find . -name "*.java")
  
      - name: PMD
        run: |
          ./pmd-bin-6.55.0/bin/run.sh pmd -d . -R rulesets/java/quickstart.xml
